api_key = "KEYYYYYYYYYYYYYYYYYYY"
audio_file = "audio.mp3"
msg_limit = 18
global_listen = false
device = "default" # windows needs this set to device name
backend = "alsa" # "dshow" for windows
# keycode = 420
# prompt = ""
